#!/bin/bash
set -e -u -o pipefail


git diff-index --quiet HEAD -- \
|| (echo "Working tree is dirty. Commit all changes."; false)

GITSHA=$(git rev-parse HEAD)
REPO=$(scripts/get-staging-repo-url)
TAG=${REPO}:${GITSHA}
NAME=$(echo $REPO | sed 's|.*/||')


docker build \
    --build-arg=GITSHA=${GITSHA} \
    --build-arg=TIMESTAMP="$(date -u '+%Y-%m-%d %H:%M:%S +0000 UTC')" \
    --compress --force-rm --pull \
    -t $TAG \
    -f ./docker/webui/Dockerfile \
    .

docker push $TAG

docker tag $TAG ${REPO}:latest

aws ecr batch-delete-image \
    --repository-name $NAME \
    --image-ids imageTag=latest

docker push ${REPO}:latest
