#!/bin/bash
set -e -u -o pipefail


git diff-index --quiet HEAD -- \
|| (echo "Working tree is dirty. Commit all changes."; false)

GITSHA=$(git rev-parse HEAD)
TIMESTAMP="$(date -u '+%Y-%m-%d %H:%M:%S +0000 UTC')"

###
# move
###
REPO=$(scripts/get-staging-repo-url move)
NAME=$(echo $REPO | sed 's|.*/||')

TAG=${REPO}:${GITSHA}
docker build \
    --build-arg=GITSHA="$GITSHA" \
    --build-arg=TIMESTAMP="$TIMESTAMP" \
    --compress --force-rm --pull \
    -t $TAG \
    -f ./docker/move/Dockerfile \
    .
docker push $TAG

docker tag $TAG ${REPO}:latest
aws ecr batch-delete-image \
    --repository-name $NAME \
    --image-ids imageTag=latest
docker push ${REPO}:latest

###
# webui
###
REPO=$(scripts/get-staging-repo-url webui)
NAME=$(echo $REPO | sed 's|.*/||')

TAG=${REPO}:${GITSHA}
docker build \
    --build-arg=GITSHA="$GITSHA" \
    --build-arg=TIMESTAMP="$TIMESTAMP" \
    --compress --force-rm --pull \
    -t $TAG \
    -f ./docker/webui/Dockerfile \
    .
docker push $TAG

docker tag $TAG ${REPO}:latest
aws ecr batch-delete-image \
    --repository-name $NAME \
    --image-ids imageTag=latest
docker push ${REPO}:latest
